{"data":[{"url":"https://api.github.com/repos/4ian/GD/issues/2","repository_url":"https://api.github.com/repos/4ian/GD","labels_url":"https://api.github.com/repos/4ian/GD/issues/2/labels{/name}","comments_url":"https://api.github.com/repos/4ian/GD/issues/2/comments","events_url":"https://api.github.com/repos/4ian/GD/issues/2/events","html_url":"https://github.com/4ian/GD/issues/2","id":37156711,"number":2,"title":"Linux: AStarAutomatism.xgdle couldn't be removed","user":{"login":"Wend1go","id":7413059,"avatar_url":"https://avatars0.githubusercontent.com/u/7413059?v=4","gravatar_id":"","url":"https://api.github.com/users/Wend1go","html_url":"https://github.com/Wend1go","followers_url":"https://api.github.com/users/Wend1go/followers","following_url":"https://api.github.com/users/Wend1go/following{/other_user}","gists_url":"https://api.github.com/users/Wend1go/gists{/gist_id}","starred_url":"https://api.github.com/users/Wend1go/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Wend1go/subscriptions","organizations_url":"https://api.github.com/users/Wend1go/orgs","repos_url":"https://api.github.com/users/Wend1go/repos","events_url":"https://api.github.com/users/Wend1go/events{/privacy}","received_events_url":"https://api.github.com/users/Wend1go/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2014-07-04T10:13:18Z","updated_at":"2014-07-04T13:17:45Z","closed_at":"2014-07-04T13:17:45Z","author_association":"CONTRIBUTOR","body":"The following error appears right at startup.\n![04 07 2014_gd_error_astarautomatism xgdle](https://cloud.githubusercontent.com/assets/7413059/3480564/8b01652c-0362-11e4-87f4-52690aeda9a2.png)\nI don't know if it has any impact on the pathfinding addons.\n\nThe error appears on both of these systems:\n- Linux Mint 16 64Bit Cinnamon (hardware machine)\n- Linux Mint 17 64Bit xfce (virtual machine on Win7 Host)\n\nBoth installed with the official \"Ubuntu 13.10 64-bits\" Deb package.\n","reactions":{"url":"https://api.github.com/repos/4ian/GD/issues/2/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0}},{"url":"https://api.github.com/repos/4ian/GD/issues/1","repository_url":"https://api.github.com/repos/4ian/GD","labels_url":"https://api.github.com/repos/4ian/GD/issues/1/labels{/name}","comments_url":"https://api.github.com/repos/4ian/GD/issues/1/comments","events_url":"https://api.github.com/repos/4ian/GD/issues/1/events","html_url":"https://github.com/4ian/GD/issues/1","id":37006926,"number":1,"title":"Build fails on archlinux64","user":{"login":"fdev31","id":238622,"avatar_url":"https://avatars3.githubusercontent.com/u/238622?v=4","gravatar_id":"","url":"https://api.github.com/users/fdev31","html_url":"https://github.com/fdev31","followers_url":"https://api.github.com/users/fdev31/followers","following_url":"https://api.github.com/users/fdev31/following{/other_user}","gists_url":"https://api.github.com/users/fdev31/gists{/gist_id}","starred_url":"https://api.github.com/users/fdev31/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fdev31/subscriptions","organizations_url":"https://api.github.com/users/fdev31/orgs","repos_url":"https://api.github.com/users/fdev31/repos","events_url":"https://api.github.com/users/fdev31/events{/privacy}","received_events_url":"https://api.github.com/users/fdev31/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":19,"created_at":"2014-07-02T17:51:36Z","updated_at":"2014-10-05T12:41:34Z","closed_at":"2014-10-03T11:58:48Z","author_association":"NONE","body":"Using _gtk-3.12.2_ and _wxgtk-3.0.0_, I get the following traceback while building on some Archlinux system:\n\n```\nIn file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30:0,\n                 from /usr/include/gtk-3.0/gdk/gdk.h:32,\n                 from /usr/include/gtk-3.0/gtk/gtk.h:30,\n                 from /tmp/gd/src/GD-build/Core/GDCore/IDE/Dialogs/ResourcesEditor.cpp:55:\n/usr/include/gtk-3.0/gdk/gdktypes.h:127:39: erreur: conflicting declaration ‘typedef struct _GdkWindow GdkWindow’\n typedef struct _GdkWindow             GdkWindow;\n                                       ^\nIn file included from /usr/include/wx-3.0/wx/treectrl.h:18:0,\n                 from /tmp/gd/src/GD-build/Core/./GDCore/IDE/Dialogs/ResourcesEditor.h:10,\n                 from /tmp/gd/src/GD-build/Core/GDCore/IDE/Dialogs/ResourcesEditor.cpp:8:\n/usr/include/wx-3.0/wx/defs.h:3396:33: note: previous declaration as ‘typedef struct _GdkDrawable GdkWindow’\n     typedef struct _GdkDrawable GdkWindow;\n                                 ^\nCore/CMakeFiles/GDCore.dir/build.make:1522: recipe for target 'Core/CMakeFiles/GDCore.dir/GDCore/IDE/Dialogs/ResourcesEditor.cpp.o' failed\nmake[2]: *** [Core/CMakeFiles/GDCore.dir/GDCore/IDE/Dialogs/ResourcesEditor.cpp.o] Error 1\nCMakeFiles/Makefile2:78: recipe for target 'Core/CMakeFiles/GDCore.dir/all' failed\nmake[1]: *** [Core/CMakeFiles/GDCore.dir/all] Error 2\nMakefile:75: recipe for target 'all' failed\nmake: *** [all] Error 2\n```\n\nIs it some familiar definition conflict to you ?\nWhat are the supported gtk/wx versions ? I'm really not sure it's a bug, or eventually in the cmake files...\n","reactions":{"url":"https://api.github.com/repos/4ian/GD/issues/1/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0}}],"meta":{"x-ratelimit-limit":"5000","x-ratelimit-remaining":"4703","x-ratelimit-reset":"1507317096","x-github-request-id":"C61B:366F:170F9C:3035B0:59D7D3AB","x-github-media-type":"github.squirrel-girl-preview","link":"<https://api.github.com/repositories/21331090/issues?state=all&page=1>; rel=\"first\", <https://api.github.com/repositories/21331090/issues?state=all&page=13>; rel=\"prev\"","etag":"\"4a9c526b708c38d43bc32e1288c8503d\"","status":"200 OK"}}
